/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-podofo.h
 #	source generated by 4D Plugin Wizard
 #	Project : podofo
 #	author : miyako
 #	2020/10/23
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PODOFO_H
#define PLUGIN_PODOFO_H

#include "4DPluginAPI.h"

#include <cstdlib>
#include <cstdio>
#include <string>
#include <iostream>

#include "openssl/bio.h"
#include "openssl/evp.h"
#include "openssl/err.h"
#include "openssl/pem.h"
#include "openssl/ssl.h"
#include "openssl/x509.h"

#if defined(_WIN64)
#define fseeko _fseeki64
#define ftello _ftelli64
#else
#define fseeko fseek
#define ftello ftell
#endif

#include "podofo/podofo.h"

#include "4DPlugin-JSON.h"

#if __APPLE__
#import <CoreFoundation/CoreFoundation.h>
#import <Cocoa/Cocoa.h>
#import <AppKit/AppKit.h>
#endif

using namespace PoDoFo;

#pragma mark -

void podofosign(PA_PluginParameters params);

#endif /* PLUGIN_PODOFO_H */
